---

replicaCount: 1

image:
  repository: docker-hub.2gis.ru/webmaps/mapgl-selfhosting
  pullPolicy: IfNotPresent
  tag: test1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

podAnnotations: {}
podLabels: {}

service:
  annotations: {}
  labels: {}
  type: NodePort
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts: 
    - paths:
        - path: /mapgl
          pathType: Prefix

  tls: []

resources: {}

nodeSelector: {}
affinity: {}
tolerations: []
podDisruptionBudget:
  enabled: true
  maxUnavailable: 1

hpa:
  enabled: false
  maxReplicas: 2
  minReplicas: 1
  targetCPUUtilizationPercentage: 80

vpa:
  enabled: false
  updateMode: Auto
  minAllowed:
    memory: 100Mi
  maxAllowed:
    cpu: 200m
    memory: 200Mi
