{{- if .Values.podDisruptionBudget.enabled }}
---

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "k8s-starter-kit-helm3.fullname" . }}
  labels:
    {{- include "k8s-starter-kit-helm3.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "k8s-starter-kit-helm3.selectorLabels" . | nindent 6 }}
{{- end }}
