---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-starter-kit-helm3.fullname" . }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "k8s-starter-kit-helm3.labels" . | nindent 4 }}
  {{- if .Values.service.labels }}
    {{- toYaml .Values.service.labels | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      appProtocol: http
  selector:
    {{- include "k8s-starter-kit-helm3.selectorLabels" . | nindent 4 }}
