{{- if .Values.vpa.enabled }}
---

apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "k8s-starter-kit-helm3.fullname" . }}
  labels:
    {{- include "k8s-starter-kit-helm3.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "k8s-starter-kit-helm3.fullname" . }}
  updatePolicy:
    updateMode: {{ .Values.vpa.updateMode }}
  resourcePolicy:
    containerPolicies:
      - containerName: {{ .Chart.Name }}
        mode: Auto
        {{- with .Values.vpa.minAllowed }}
        minAllowed:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.vpa.maxAllowed }}
        maxAllowed:
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{- end }}
